name: deploy-app

on: 
  push:
    branches: 
      - feature-deploy
  
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: nodejs
        uses: actions/setup-node@v4 
        with: 
          node-version: '20' # Specify your required Node version (e.g., 18, 20, 22)
          cache: 'npm' 
          
      - name: npminstall
        run: npm install

      - name: npmtest
        run: npm test
